### PR TITLE
Translated the entire file

### PR DESCRIPTION
**Pull request by Blask0**
Updated the spanish translation , review in case there´s something wrong.

### CODE REVIEW

**Comment by shivareddyiirs** [comment]
Hey do check the latest updated version of .ts file and translate the unfinished ones

**Comment by Blask0** [comment]
How I do that?, I’m new sorry.

**Comment by shivareddyiirs** [comment]
Can you please make a new commit to this PR with latest changes in the QRealTime4.0 branch.

**Comment by shivareddyiirs** [comment]
Please raise a new pull request

**Pull request closed without merging**
