### PR TITLE
Fixed getTable and added Make Online functionality

### PR DESCRIPTION
**Pull request by ianmahoney1**

### CODE REVIEW

**Review by shivareddyiirs — COMMENTED** [review]
Can you attach screenshots for successful import , sync and make online.

**Review by shivareddyiirs — CHANGES_REQUESTED** [review]
SendForm is the method which needs to be overridden. Why  we need to override  'prepareSendForm' and 'getFieldsModel ' is not clear as it is already available in parent class i.e. KOBO

**Comment by ianmahoney1** [comment]
SendForm requires prepareSendForm and getFieldsModel, which were overridden in KOBO from Aggregate. The structure and what is required in the KOBO prepareSendForm and getFieldsModel methods is such that it does not work for Central, so it needs to be overridden again to be the correct format.

**Comment by shivareddyiirs** [comment]
> SendForm requires prepareSendForm and getFieldsModel, which were overridden in KOBO from Aggregate. The structure and what is required in the KOBO prepareSendForm and getFieldsModel methods is such that it does not work for Central, so it needs to be overridden again to be the correct format.

I see because you are using xform in xml format to push to odk central. Is it possible to push in JSON format like KOBO? IF yes , then we should go for JSON format. There are two reasons for it:

1. JSON is easy to handle in python
2. we want to remove dependency om pyxform library. Probably remove that dependency completely in future version.

Please let me know if it is doable , otherwise we can merge this pull request as it is.

**Comment by ianmahoney1** [comment]
I fixed a couple of indentation issues that arose, so that should be reflected in the second commit. Unfortunately, it is not possible to push in JSON format like KOBO, so the override was necessary to use xform in xml format. Also, here are some screenshots of the sync, import, and make online.

Import
Sync
Make Online
Make Online Result

**Comment by shivareddyiirs** [comment]
Now can you please test plugin with all three servers(aggregate, kobo and Central) and if everything is fine , then let me know so that it can be uploaded as new version into QGIS plugin repository.

Also do update  in readme file of plugin reflecting recent changes

**Pull request merged**
