### PR TITLE
feature/syncfunction

### PR DESCRIPTION
**Pull request by chandnirajasekaran**
Added import and sync functionality for ODK Central.

Example of imported data:
Screen Shot 2021-02-26 at 9 40 45 AM

Supports point, line, and polygon geometry types.

### CODE REVIEW

**Comment by chandnirajasekaran** [comment]
Currently, I tested the code using forms that contain points, lines and polygons for the shape fields, and the geodata seems to be appearing on QGIS map, and the rest of the data shows up in the 'Attributes Table' on QGIS.

**Comment by shivareddyiirs** [comment]
make online functionality and sync functionality also tested?

**Comment by chandnirajasekaran** [comment]
While writing out the functions for the sync and import functionality, a lot of the code seemed to be similar to the Kobo Class. It looks like both classes have a "sibling" relationship to some extent. In the last PR, you mentioned that the Kobo class should be extended by Central, so right now, I have created the Central class by working off of the current Kobo Class functions. 

Due to the similarity to some extent between these two classes, would you suggest it would be better to re-structure the code where both Kobo and Central are sub-class extending from a single class (polymorphism), just for readability purposes, or leave it as is? This change wouldn't affect the current functionality.

**Comment by chandnirajasekaran** [comment]
No, we are still working on the 'make online' function. Only 'import' and 'sync' have been tested so far, and we wanted to run it by you.

**Comment by shivareddyiirs** [comment]
> oly

Yes, you are right go ahead.
Regarding pull requests you can make all pull request to **ODK_Central** branch till we have all features  added and tested.

**Comment by shivareddyiirs** [comment]
> No, we are still working on the 'make online' function. Only 'import' and 'sync' have been tested so far, and we wanted to run it by you.

Please make pull request to odk_central branch ,

**Pull request closed without merging**
